[build]
  publish = "."
  command = "echo 'No build needed'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Özel olarak query parametreleri için
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200